version: '3.3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'default'
      MYSQL_USER: 'default'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./.data/mysql:/var/lib/mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge